import { useEffect, useState } from "react";
import { ArrowRight, Check, X } from "lucide-react";
import { Form } from "../types";
import { Brand } from "./Shared";

export function PublicForm({ form, close, submit, isPreview }: { form: Form; close: () => void; submit: (answers: Record<string, string>) => void; isPreview?: boolean }) {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [done, setDone] = useState(false); 
  const question = form.questions?.[step]; 
  const answer = question ? (answers[question.id] || "") : "";
  const next = () => { if (!question) return; if (question.required && !answer.trim()) return setError("Please answer this question to continue."); if (question.type === "email" && answer && !/^\S+@\S+\.\S+$/.test(answer)) return setError("Enter a valid email address."); setError(""); if (step === form.questions.length - 1) { if (!isPreview) submit(answers); setDone(true); } else setStep(current => current + 1); };
  useEffect(() => {
    const handleKey = (e: globalThis.KeyboardEvent) => {
      if (!question) return;
      const tag = document.activeElement?.tagName; const isInput = tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT";
      if (e.key === "Enter") { if (question.type === "long_text" && !e.ctrlKey && !e.metaKey) return; e.preventDefault(); next(); }
      else if ((e.key === "ArrowRight" || e.key === "ArrowDown") && !isInput) { e.preventDefault(); next(); }
      else if ((e.key === "ArrowLeft" || e.key === "ArrowUp") && !isInput && step > 0) { e.preventDefault(); setStep(s => s - 1); }
    };
    window.addEventListener("keydown", handleKey); return () => window.removeEventListener("keydown", handleKey);
  });
  if (!question) return <div className="public-form"><button className="public-close" onClick={close}><X size={19} /> Close</button><div className="thank-you"><p className="eyebrow">EMPTY FORM</p><h1>This form has no questions.</h1><p>Please add some questions in the editor before previewing.</p><button className="button dark" onClick={close}>Back to editor</button></div></div>;
  if (done) return <div className="public-form"><button className="public-close" onClick={close}><X size={19} /> Close</button><div className="thank-you"><div className="success-mark"><Check size={32} /></div><p className="eyebrow">ALL DONE</p><h1>{isPreview ? "Preview complete" : (form.thank_you_message ?? "Thank you for sharing.")}</h1><p>{isPreview ? "Your response was not recorded because this is a preview." : "Your response has been recorded. We really appreciate your time."}</p><button className="button dark" onClick={close}>Back to editor</button></div></div>;
  return <div className="public-form"><button className="public-close" onClick={close}><X size={19} /> {isPreview ? "Close preview" : "Close"}</button><div className="public-brand"><Brand /></div><div className="progress"><i style={{ width: `${((step + 1) / form.questions.length) * 100}%` }} /></div><section className="respondent-question" key={question.id}><div className="public-number">{step + 1} <span>→</span></div><h1>{question.title}</h1>{question.description && <p>{question.description}</p>}<div className="answer-area">{question.type === "multiple_choice" ? <div className="public-choices">{question.options?.map((option, index) => <button className={answer === option ? "selected" : ""} key={option} onClick={() => setAnswers({ ...answers, [question.id]: option })}><kbd>{String.fromCharCode(65 + index)}</kbd>{option}</button>)}</div> : question.type === "yes_no" ? <div className="public-choices yes"><button className={answer === "Yes" ? "selected" : ""} onClick={() => setAnswers({ ...answers, [question.id]: "Yes" })}>Yes</button><button className={answer === "No" ? "selected" : ""} onClick={() => setAnswers({ ...answers, [question.id]: "No" })}>No</button></div> : question.type === "rating" ? <div className="public-rating">{[1,2,3,4,5].map(value => <button className={Number(answer) >= value ? "lit" : ""} key={value} onClick={() => setAnswers({ ...answers, [question.id]: String(value) })}>★</button>)}</div> : question.type === "dropdown" ? <select value={answer} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })}><option value="">Select an option</option>{question.options?.map(option => <option key={option}>{option}</option>)}</select> : question.type === "long_text" ? <textarea autoFocus value={answer} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })} placeholder="Type your answer here..." /> : <input autoFocus type={question.type === "email" ? "email" : question.type === "number" ? "number" : "text"} value={answer} onChange={event => setAnswers({ ...answers, [question.id]: event.target.value })} placeholder="Type your answer here..." />}</div>{error && <p className="validation">{error}</p>}<div style={{ display: "flex", gap: "10px", alignItems: "center", marginTop: "26px" }}>{step > 0 && <button className="continue" style={{ margin: 0, background: "transparent", color: "#6e6761", border: "1px solid #d2ccc5" }} onClick={() => setStep(s => s - 1)}>Back</button>}<button className="continue" style={{ margin: 0 }} onClick={next}>{step === form.questions.length - 1 ? "Submit" : "OK"} <ArrowRight size={17} /></button></div><small className="keyboard">press <kbd>Enter ↵</kbd> or arrows to continue</small></section><footer className="public-footer"><span>{step + 1} of {form.questions.length}</span></footer></div>;
}
