import React from "react";

export function Brand() { 
  return <div className="brand"><span className="brand-mark">F</span><span>formly</span></div>; 
}

export function Pill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "green" | "orange" }) { 
  return <span className={`pill ${tone}`}>{children}</span>; 
}

export function Styles() { 
  return <style dangerouslySetInnerHTML={{ __html: `.card-main{background:none;border:0;text-align:left;padding:6px 17px;width:100%;cursor:pointer}.card-main h3{font-size:16px;margin:0}.card-main p{font-size:12px;color:#918a84;margin:7px 0}.form-card footer>span:last-child{display:flex;align-items:center;gap:3px}.drag-hint{color:#9b948e;font-size:10px;padding:0 8px 9px;margin:0}.dragging{opacity:.45}.modal-backdrop{position:fixed;z-index:30;inset:0;background:#241f1b66;display:grid;place-items:center;padding:20px}.share-modal,.response-detail{position:relative;background:#fff;border-radius:15px;width:min(540px,100%);padding:35px;box-shadow:0 20px 70px #0003}.share-modal h2,.response-detail h2{font-family:'Playfair Display',serif;font-size:30px;letter-spacing:-1px;margin:0 0 8px}.share-modal>p:not(.eyebrow){color:#756f69;font-size:14px}.close-modal{position:absolute;right:16px;top:15px;border:0;background:#f1eeeb;border-radius:7px;padding:6px;color:#685f59}.share-link{display:flex;border:1px solid #ddd7d0;border-radius:8px;overflow:hidden;margin:23px 0 16px}.share-link input{min-width:0;flex:1;border:0;padding:12px;font-size:12px;color:#6b635c;outline:0}.share-link button{border:0;background:#292522;color:#fff;padding:0 13px;display:flex;gap:6px;align-items:center;font-size:12px;font-weight:600}.open-link{color:#584bd4;display:flex;gap:6px;align-items:center;width:max-content;font-size:13px;font-weight:600;text-decoration:none}.response-button{width:100%;background:#fff;border-left:0;border-right:0;border-bottom:0;text-align:left;color:inherit;cursor:pointer}.response-button:hover{background:#faf9f7}.detail-time{color:#857d77;font-size:13px;margin-top:-3px}.answer-list{margin-top:25px;display:grid;gap:0;border-top:1px solid #e9e6e2}.answer-list div{padding:15px 0;border-bottom:1px solid #e9e6e2;display:grid;gap:7px}.answer-list span{font-size:12px;color:#827a73}.answer-list b{font-size:14px;line-height:1.4}.notice{position:fixed;right:25px;bottom:25px;z-index:40;background:#282522;color:white;padding:12px 15px;border-radius:8px;display:flex;gap:8px;align-items:center;font-size:13px;box-shadow:0 8px 20px #0003}@media(max-width:700px){.share-modal,.response-detail{padding:28px 22px}.builder{min-width:650px}.response-button{grid-template-columns:1fr auto}.response-button>span:nth-child(3){grid-column:1}.response-button>svg{grid-column:2;grid-row:1}}` }} />; 
}
